name: Checks code
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Check code
      run: npm run lint
    - name: Integration tests
      run: npm run tests:integration
